import Link from "next/link";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { appSettings, students } from "@/lib/db/schema";
import { createSeries } from "../actions";

export const dynamic = "force-dynamic";
export default async function NewSeriesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const [{ error }, [settings], studentRows] = await Promise.all([searchParams, db.select().from(appSettings).where(eq(appSettings.id, 1)), db.select().from(students)]);
  const current = settings ?? { defaultCourtPriceCents: 2000, rateIndividualCents: 1800, defaultDurationMin: 60 };
  return <main className="mx-auto min-h-screen max-w-2xl px-5 pb-12 pt-8"><Link href="/calendar" className="text-sm font-bold text-emerald-700">← Volver al calendario</Link><h1 className="mt-6 text-3xl font-black">Serie semanal</h1><p className="mt-2 text-slate-500">Genera varias clases de una vez.</p>{error && <p className="mt-4 rounded-xl bg-red-50 px-3 py-2 text-sm font-bold text-red-700">Revisa el tipo y el número de alumnos.</p>}<form action={createSeries} className="mt-8 space-y-5 rounded-2xl border border-slate-200 bg-white p-5"><label className="block text-sm font-bold">Tipo<select name="type" defaultValue="individual" className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-3"><option value="individual">Individual · 1 alumno</option><option value="pair">Pareja · 2 alumnos</option><option value="group">Grupo · 3 o 4 alumnos</option></select></label><label className="block text-sm font-bold">Día<select name="weekday" defaultValue="1" className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-3"><option value="1">Lunes</option><option value="2">Martes</option><option value="3">Miércoles</option><option value="4">Jueves</option><option value="5">Viernes</option><option value="6">Sábado</option><option value="0">Domingo</option></select></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold">Primera fecha<input name="startsOn" type="date" required className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-3" /></label><label className="block text-sm font-bold">Hora<input name="timeOfDay" type="time" required defaultValue="18:00" className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-3" /></label></div><label className="block text-sm font-bold">Número de semanas<input name="weeks" type="number" min="1" max="52" defaultValue="4" className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-3" /></label><div><p className="text-sm font-bold">Alumnos</p><div className="mt-2 space-y-2">{studentRows.map((student) => <label key={student.id} className="flex min-h-12 items-center gap-3 rounded-xl border border-slate-200 px-3 text-sm"><input name="studentIds" value={student.id} type="checkbox" className="h-5 w-5 accent-emerald-800" />{student.firstName} {student.lastName}</label>)}</div></div><div className="grid gap-5 sm:grid-cols-2"><MoneyField name="courtPriceCents" label="Precio pista" value={current.defaultCourtPriceCents} /><MoneyField name="ratePerStudentCents" label="Precio clase / alumno" value={current.rateIndividualCents} /></div><label className="block text-sm font-bold">Duración<input name="durationMin" type="number" min="1" defaultValue={current.defaultDurationMin} className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-3" /></label><button className="min-h-12 w-full rounded-xl bg-emerald-800 font-bold text-white">Crear serie</button></form></main>;
}
function MoneyField({ name, label, value }: { name: string; label: string; value: number }) { return <label className="block text-sm font-bold">{label}<input name={name} type="number" min="0" step="0.01" inputMode="decimal" defaultValue={(value / 100).toFixed(2)} className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-slate-50 px-3" /></label>; }
