import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { classStudents, classes, paymentLines, students } from "@/lib/db/schema";
import { updateClass } from "../actions";
import { BackLink } from "@/components/ui/back-link";
import { Input, Select, Textarea, Field } from "@/components/ui/field";
import { MoneyInput } from "@/components/ui/money-input";

export const dynamic = "force-dynamic";

export default async function EditClassPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string }> }) {
  const [{ id }, { error }] = await Promise.all([params, searchParams]);
  const [[item], studentRows, selectedRows, paymentRows] = await Promise.all([db.select().from(classes).where(eq(classes.id, id)), db.select().from(students).where(eq(students.active, true)), db.select({ studentId: classStudents.studentId }).from(classStudents).where(eq(classStudents.classId, id)), db.select({ paymentId: paymentLines.paymentId }).from(paymentLines).where(eq(paymentLines.classId, id)).limit(1)]);
  if (!item) return <main className="mx-auto max-w-3xl"><BackLink href="/calendar" label="Volver al calendario" /><p className="mt-6">Clase no encontrada.</p></main>;
  const selected = new Set(selectedRows.map((row) => row.studentId));
  const localDateTime = new Date(item.startsAt.getTime() - item.startsAt.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  return <main className="mx-auto min-h-screen max-w-3xl pb-12"><BackLink href={`/classes/${id}`} label="Volver a la clase" /><h1 className="mt-6 text-3xl font-black">Editar clase</h1>{error && <p className="mt-4 rounded-xl bg-red-50 px-3 py-2 text-sm font-bold text-red-700">El tipo debe coincidir con el número de alumnos.</p>}{paymentRows.length > 0 && <p className="mt-4 rounded-xl bg-amber-50 px-4 py-3 text-sm font-bold text-amber-800">Esta clase ya está incluida en un pago generado. Si cambias su estado o sus precios, vuelve a pulsar &quot;Generar pagos&quot; en el mes correspondiente.</p>}<form action={updateClass.bind(null, id)} className="mt-8 grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 lg:grid-cols-2"><Field label="Tipo"><Select name="type" defaultValue={item.type}><option value="individual">Individual · 1 alumno</option><option value="pair">Pareja · 2 alumnos</option><option value="group">Grupo · 3 o 4 alumnos</option></Select></Field><Field label="Estado"><Select name="status" defaultValue={item.status}><option value="pending">Pendiente</option><option value="completed">Terminada</option><option value="cancelled">Cancelada</option></Select></Field><Field label="Fecha y hora"><Input name="startsAt" type="datetime-local" required defaultValue={localDateTime} /></Field><div className="lg:col-span-2"><p className="text-sm font-bold">Alumnos</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{studentRows.map((student) => <label key={student.id} className="flex min-h-12 items-center gap-3 rounded-xl border border-slate-200 px-3 text-sm"><input name="studentIds" value={student.id} defaultChecked={selected.has(student.id)} type="checkbox" className="h-5 w-5 accent-emerald-800" />{student.firstName} {student.lastName}</label>)}</div></div><Field label="Precio pista"><MoneyInput name="courtPriceCents" defaultValue={(item.courtPriceCents / 100).toFixed(2)} /></Field><Field label="Precio clase / alumno"><MoneyInput name="ratePerStudentCents" defaultValue={(item.ratePerStudentCents / 100).toFixed(2)} /></Field><Field label="Duración"><Input name="durationMin" type="number" min="1" defaultValue={item.durationMin} /></Field><Field label="Comentario"><Textarea name="notes" defaultValue={item.notes ?? ""} /></Field><button className="min-h-12 w-full rounded-xl bg-emerald-800 font-bold text-white lg:col-span-2 lg:w-fit lg:px-6">Guardar cambios</button></form></main>;
}
