"use client";
import { useRef, useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight } from "lucide-react";
import { useRouter } from "next/navigation";

const weekdays = ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"];

export function MonthPicker({ year, month, selectedDay }: { year: number; month: number; selectedDay: string }) {
  const dialogRef = useRef<HTMLDialogElement>(null); const router = useRouter(); const [view, setView] = useState({ year, month }); const cells = getPickerCells(view.year, view.month); const title = new Date(Date.UTC(view.year, view.month - 1, 1)).toLocaleDateString("es-ES", { month: "long", year: "numeric" });
  function selectDay(date: string) { const [selectedYear, selectedMonth] = date.split("-").map(Number); dialogRef.current?.close(); router.push(`/calendar?year=${selectedYear}&month=${selectedMonth}&day=${date}`); }
  return <><button type="button" onClick={() => { setView({ year, month }); dialogRef.current?.showModal(); }} aria-label="Elegir día" className="inline-flex items-center gap-2 text-lg font-bold capitalize">{new Date(`${selectedDay}T12:00:00Z`).toLocaleDateString("es-ES", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}<ChevronDown size={20} className="text-slate-500" /></button><dialog ref={dialogRef} className="m-auto w-[calc(100%-2rem)] max-w-md overflow-hidden rounded-3xl border border-slate-200 bg-white p-0 shadow-2xl backdrop:bg-slate-950/50"><div className="bg-emerald-800 p-4 text-white"><div className="flex items-center justify-between"><button type="button" aria-label="Mes anterior" onClick={() => setView(previousMonth(view.year, view.month))} className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-900"><ChevronLeft size={22} /></button><h2 className="text-lg font-black capitalize">{title}</h2><button type="button" aria-label="Mes siguiente" onClick={() => setView(nextMonth(view.year, view.month))} className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-900"><ChevronRight size={22} /></button></div><div className="mt-4 grid grid-cols-7 text-center text-xs font-bold uppercase">{weekdays.map((day) => <span key={day}>{day}</span>)}</div></div><div className="grid grid-cols-7 gap-y-2 p-4">{cells.map((cell) => <button key={cell.date} type="button" onClick={() => selectDay(cell.date)} className={`flex h-11 items-center justify-center rounded-full text-sm font-bold ${cell.monthOffset !== 0 ? "text-slate-300" : "text-slate-700"} ${cell.date === selectedDay ? "bg-emerald-600 text-white" : "hover:bg-emerald-50"}`}>{cell.day}</button>)}</div></dialog></>;
}

function previousMonth(year: number, month: number) { return month === 1 ? { year: year - 1, month: 12 } : { year, month: month - 1 }; }
function nextMonth(year: number, month: number) { return month === 12 ? { year: year + 1, month: 1 } : { year, month: month + 1 }; }
function getPickerCells(year: number, month: number) { const first = new Date(Date.UTC(year, month - 1, 1)); const offset = first.getUTCDay() === 0 ? 6 : first.getUTCDay() - 1; const total = new Date(Date.UTC(year, month, 0)).getUTCDate(); const previousTotal = new Date(Date.UTC(year, month - 1, 0)).getUTCDate(); const cells = Array.from({ length: offset }, (_, index) => { const day = previousTotal - offset + index + 1; const date = new Date(Date.UTC(year, month - 2, day)); return { date: date.toISOString().slice(0, 10), day, monthOffset: -1 }; }); cells.push(...Array.from({ length: total }, (_, index) => ({ date: `${year}-${String(month).padStart(2, "0")}-${String(index + 1).padStart(2, "0")}`, day: index + 1, monthOffset: 0 }))); const trailing = (7 - (cells.length % 7)) % 7; cells.push(...Array.from({ length: trailing }, (_, index) => { const date = new Date(Date.UTC(year, month, index + 1)); return { date: date.toISOString().slice(0, 10), day: index + 1, monthOffset: 1 }; })); return cells; }
