import Link from "next/link";
import { buildCalendarHref, type StripDay } from "@/lib/calendar";
import { StripScroller } from "./strip-scroller";
import { MonthPicker } from "./month-picker";

export function WeekStrip({ days, selectedDay, year, month, classDays, selectedClassCount = 0 }: { days: StripDay[]; selectedDay: string; year: number; month: number; classDays: Set<string>; selectedClassCount?: number }) {
  const weeks = Array.from(new Set(days.map((day) => day.weekStart)));
  return <section className="lg:hidden"><div className="flex items-center justify-center"><MonthPicker year={year} month={month} selectedDay={selectedDay} /></div><StripScroller selectedWeek={days.find((day) => day.date === selectedDay)?.weekStart}><div className="flex min-w-full snap-x snap-mandatory overflow-x-auto py-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{weeks.map((weekStart) => <div key={weekStart} data-week={weekStart} className="grid min-w-full snap-center grid-cols-7 gap-1"><>{days.filter((day) => day.weekStart === weekStart).map((day) => <Link key={day.date} href={buildCalendarHref("/calendar", year, month, day.date)} className="flex min-h-20 flex-col items-center justify-center gap-1"><span className={`text-sm capitalize ${day.date === selectedDay ? "text-emerald-700" : "text-slate-700"}`}>{day.weekdayLabel}</span><span className={`flex h-11 w-11 items-center justify-center rounded-full text-lg font-bold ${day.date === selectedDay ? "bg-emerald-800 text-white" : day.isToday ? "ring-2 ring-emerald-800" : ""}`}>{day.dayNumber}</span>{classDays.has(day.date) && <span className="h-1.5 w-1.5 rounded-full bg-lime-500" />}</Link>)}</></div>)}</div></StripScroller><p className="text-center text-sm text-slate-500">{selectedClassCount} {selectedClassCount === 1 ? "clase" : "clases"}</p></section>;
}
